### ISSUE TITLE
No Tweak Installer code

### ISSUE THREAD

**Issue by daniel63194** [josephwalden13/tweak-installer#1]
As i can see, there is only the open source of the Unjailbreaker software. No Tweak Installer code. Are you going to release it as i want to improve the UI.

**Comment by josephwalden13** [comment]
Unjailbreaker is the tweak installer (tic.exe). It's called unjailbreaker as its original purpose was to remove to.panga. Tweak installer.exe just calls command line arguments on tic.exe. I'll push Tweak Installer GUI to another repo in a sec. A better UI would be great :)

**Comment by josephwalden13** [comment]
https://github.com/josephwalden13/Tweak-Installer-GUI
:)
