### ISSUE TITLE
Error while install themes.. (no Themes folder)

### ISSUE THREAD

**Issue by nickch99** [josephwalden13/tweak-installer#10]
Maybe you just forgot to create Themes folder in /System/Library. ?
If i create "Themes" folder by ssh, it's ok to install..
But after i uninstall the theme.."Themes" folder is gone... i had to create the folder again..

**Comment by josephwalden13** [comment]
Added precaution to stop Themes folder from being deleted
I have just pushed a fix for this so you can wait for the next beta or download the updated version of this file and place it in your Tweak Installer directory
https://github.com/josephwalden13/tweak-installer/blob/master/bin/Debug/tic.exe?raw=true
