### ISSUE TITLE
Background Processes Don't Close

### ISSUE THREAD

**Issue by Rakumon23** [josephwalden13/tweak-installer#11]
If you close the program after it has been opened the background process for WinSCP stays open. So, when I used old versions and then updated to several new ones they all had their own WinSCP process going on in the background even though all of them were closed. This also meant that I could not delete the folders they were installed in until I manually ended the processes in the task manager.

**Comment by josephwalden13** [comment]
Forgot to include session.Close(); 
I have just pushed a fix for this so you can wait for the next beta or download the updated version of this file and place it in your Tweak Installer directory
https://github.com/josephwalden13/tweak-installer/blob/master/bin/Debug/tic.exe?raw=true

**Comment by Rakumon23** [comment]
Thanks!
