### ISSUE TITLE
Save settings on other options

### ISSUE THREAD

**Issue by Geczy** [josephwalden13/tweak-installer#12]
Not just on install

Save settings when respring

**Comment by josephwalden13** [comment]
What do you mean by save settings? Which settings?

**Comment by Geczy** [comment]
The `settings` file

**Comment by josephwalden13** [comment]
The settings file contains 3 lines, username, password, and IP. It saves whenever you change a value. I'm not sure what you're trying to suggest, sorry.

**Comment by josephwalden13** [comment]
Anything changeable now retains values. I’ll push it later
