### ISSUE TITLE
update does work

### ISSUE THREAD

**Issue by kavianr** [josephwalden13/tweak-installer#13]
hello, whenever i open the TIC.exe and it says connecting then it says tweak installer has stopped working and this is what shows in command line

Connecting

Unhandled Exception: System.ArgumentException: SessionOptions.Password is set, but SessionOptions.UserName is not.
   at WinSCP.Session.SessionOptionsToUrlAndSwitches(SessionOptions sessionOptions, Boolean scanFingerprint, String& command, String& log)
   at WinSCP.Session.Open(SessionOptions sessionOptions)
   at Unjailbreaker.Program.Main(String[] args)

**Comment by josephwalden13** [comment]
I’ll look into it. For know you can fix it by opening the file  settings in notepad  and adding “root” to the blank line. There should be 3 lines in total

**Comment by kavianr** [comment]
thank you, that i think solved it, now after connecting it just closes. on beta 9.1

**Comment by josephwalden13** [comment]
Make sure ssh and sftp ports are open and sftp is installed on the phone, make sure you are jailbroken and make sure you set the correct ip. This is not a problem with my tool

**Comment by kavianr** [comment]
thank you, i think there was a misunderstanding on my part, i thought the TIC.exe was for updating the tool, sorry about that.
the tool works flawlessly. i just thought updating from beta 6 to 9.1 you had to open the TIC.exe.
sorry. best regards
