### ISSUE TITLE
Cant uninstall IPA

### ISSUE THREAD

**Issue by GOODTESTA** [josephwalden13/tweak-installer#15]
![image](https://user-images.githubusercontent.com/35817374/35410607-f4d7a4fc-0250-11e8-971a-d7ee8c153cad.png)

Can I delete ipa file I installed , but there is something wrong
Cannot access the dictionary....
 thank you ^^

**Comment by josephwalden13** [comment]
Have you got either 'files' or 'temp' open in explorer, because that would prevent them from deleting, which is what the tool was trying to do so it could extract the ipa without old files being present. Try deleting the folders 'temp' and 'files' yourself and see if that works.

**Comment by GOODTESTA** [comment]
BTW, the ipa is "Source" where I download it in yalu
I install the IPA successfully, but cannot uninstall.
https://yalujailbreak.net/source-helper/

**Comment by josephwalden13** [comment]
Have you got either 'files' or 'temp' open in explorer, because that would prevent them from deleting, which is what the tool was trying to do so it could extract the ipa without old files being present. Try deleting the folders 'temp' and 'files' yourself and see if that works.

**Comment by GOODTESTA** [comment]
Thank you, It's works after I delete the folder "files"
I'm using tweak installer, and the program file is sync in my google drive.
Maybe google drive sync the folder and make the folder("files") unreadable.
I'm wondering the folder "files" and "temp" can be generated at the system temp folder instead of the pogram running folder or not.
Hope you have a good day.

**Comment by josephwalden13** [comment]
Actually that’s a good idea. I’ll move them to %appdata%. Thanks, you too
