### ISSUE TITLE
CCUnrestrict

### ISSUE THREAD

**Issue by D1mar0n** [josephwalden13/tweak-installer#18]
Hi! Thank you so much for the program! She is just gorgeous! 10+!
With the tweak CCUnrestrict there is a problem: after I delete my notification center is left completely empty! I guess deletion is incorrect. please see what you can do and how to fix it.

`iPhone 7 iOS 11.1.2`

**Comment by josephwalden13** [comment]
I linked another file to restore the original layout. 
https://github.com/josephwalden13/tweak-installer/blob/master/my%20tweaks/ccrestrict.zip?raw=true
All of the modules are currently available to add in settings, but this file will restore it to default

**Comment by D1mar0n** [comment]
Thanks for the answer! Applied your files. Now it's like this - watch the video.


Отправлено с iPhone

**Comment by D1mar0n** [comment]
View [video](https://www.upload.ee/files/7940225/IMG_0575.7z.html) please.

**Comment by D1mar0n** [comment]
After several reinstalls it worked fine. Thank you very much! With impatience I will wait Your new creations. ))

**Comment by josephwalden13** [comment]
Oh thats really weird :D. Glad its fixed now. I think it probably needed a respring after the initial loading of the file, which reinstalling did

**Comment by D1mar0n** [comment]
Already everything is fine!

На 26.01.2018 14:35:32, josephwalden13 <notifications@github.com> писал:
Oh thats really weird :D. Glad its fixed now. I think it probably needed a respring after the initial loading of the file, which reinstalling did
