### ISSUE TITLE
it requires sta mode

### ISSUE THREAD

**Issue by byek990** [josephwalden13/tweak-installer#19]
![default](https://user-images.githubusercontent.com/35845041/35449367-2a4d2828-0300-11e8-9efb-7ffd4b9e45f6.png)

**Comment by josephwalden13** [comment]
Try version 1.0.3
https://github.com/josephwalden13/tweak-installer/releases/download/v1.0.3/v1.0.3.zip

Also, double check your IP address and root password. If the problem persists try rebooting your phone
