### ISSUE TITLE
Rebooting Issue after install [IPA's]

### ISSUE THREAD

**Issue by ghost** [josephwalden13/tweak-installer#2]
There seems to be many users complaining about an issue with installing IPA's using the tool. Manually signing is working but there's a problem with the tool. I'm running the tool on Windows 10 x64 and the iPhone X I'm using is running 11.1.12 with Electra B7 JB.

The way it works for me:
Extracting .IPA, moving to /Applications/ via SFTP then running the below commands in the /Applications/(app here) folder:
jtool --ent /bin/ps > platform.ent
jtool -e arch -arch arm64 Plex
jtool --sign --ent platform.ent --inplace Plex.arch_arm64
mv Plex.arch_arm64 Plex
rm Plex.arch_arm64
uicache

Screenshot of the tool's output: https://i.imgur.com/V2TYanq.png

**Comment by josephwalden13** [comment]
Yup. I have fixed the signing issue so now it should only sign Plex. It was a stupid issue but its fixed now. I'm not sure if it'll fix the reboots so I'm gonna get someone to test it quickly and if that works I'll release it as an update. Thanks for the information. It has been helpful :)

**Comment by ghost** [comment]
The ~/plat.ent being empty is being the cause of the issue rebooting since it adds empty entitlements to the app. I've executed "jtool --ent /bin/ps > ~/plat.ent" manually via ssh then ran your tool again and it worked. The command gives an empty file on first run for some reason with your tool and the next times it uses the empty file it creates to give entitlements. Also please revert to the old version + the fix for the entitlement command because it only signs the binary in the first folder.

**Comment by josephwalden13** [comment]
I’ll keep this open until it’s fixed so others can see

**Comment by josephwalden13** [comment]
From what I hear it’s fixed :)
