### ISSUE TITLE
Error when installing themes.deb

### ISSUE THREAD

**Issue by inhumanargue** [josephwalden13/tweak-installer#20]
Hello whom it may reach,

I've been using tweak installer now for some time. this is the first time however that I have tried to install themes with it. I am getting the following errors on v1.0.1 Windows 10.

![tweak installer error](https://user-images.githubusercontent.com/35850414/35458148-429fe3fe-02a9-11e8-9e22-295fb8372a9b.jpg)

**Comment by josephwalden13** [comment]
I fixed a similar bug in version 1.0.3. It could be the same cause so please could you update and try again :)

**Comment by inhumanargue** [comment]
Thank you so much for the speedy response! I’ll go grab that now!
