### ISSUE TITLE
Error when trying to install tweaks. 

### ISSUE THREAD

**Issue by csamples22** [josephwalden13/tweak-installer#21]
Hi, I've been trying to install tweaks using the .deb files, and i keep getting an error message.
This is what it says when I try to install.

Connecting
Unknown Error. Please use the big red bug report link and include some form of crash report. Error report copying to clipboard.

Unhandled Exception: System.Threading.ThreadStateException: Current thread must be set to single thread apartment (STA) mode before OLE calls can be made. Ensure that your Main function has STAThreadAttribute marked on it.
   at System.Windows.Forms.Clipboard.SetDataObject(Object data, Boolean copy, Int32 retryTimes, Int32 retryDelay)
   at System.Windows.Forms.Clipboard.SetText(String text, TextDataFormat format)
   at System.Windows.Forms.Clipboard.SetText(String text)
   at Unjailbreaker.Program.Main(String[] args)

**Comment by josephwalden13** [comment]
That error message is an error message for displaying the error message. My error message crashed :(. I’ll need to fix that bug :D. Your problem is an issue with ssh / sftp. Make sure that your ip and root password are correct. If they are and it still happens reboot your phone, rejailbreak and upgrade to tweak installer 1.0.3 if you haven’t already and hopefully it’ll work

**Comment by byek990** [comment]
are you ios10 with meridian jb(i7)?

**Comment by D1mar0n** [comment]
I have here such errors happen when you try to install any themes...
```
Unhandled exception: System.IO.DirectoryNotFoundException: Could not find part of the path.
in System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
in System.IO.Directory.InternalMove(String sourceDirName, String destDirName, Boolean checkHost)
in System.IO.Directory.Move(String sourceDirName, String destDirName)
in Unjailbreaker.Program.moveDirIfPresent(String source, String dest, String parent)
in Unjailbreaker.Program.Main(String[] args)
```

**Comment by josephwalden13** [comment]
Try with version 1.1.1 and Electra beta 9 
(Electra beta 9 changed things)

**Comment by D1mar0n** [comment]
Thanks!!!

На 27.01.2018 14:31:29, josephwalden13 <notifications@github.com> писал:
Try with version 1.1.1 and Electra beta 9
(Electra beta 9 changed things)
