### ISSUE TITLE
not working meridian jb i7 10.3

### ISSUE THREAD

**Issue by byek990** [josephwalden13/tweak-installer#22]
is it working on meridian jb?? i7+ ios 10.3 it isnt working on i7+(ios10.3 meridian jb) it says SSH connection refused (password and ip address correct. i check it several times)

**Comment by byek990** [comment]
i7+ ios 10.3

**Comment by josephwalden13** [comment]
It will work if you have SFTP installed. You will have to install it manually using this http://coolstar.org/publicrepo/debs/scp-sftp-dropbear.deb or through Cydia if you can get it to launch

**Comment by byek990** [comment]
meridian jb isnt working cydia how can i install deb file?

**Comment by josephwalden13** [comment]
You can extract the deb with Filza and copy the files from “usr/bin” inside the extracted deb to /usr/bin

To install Filza use this tutorial by the creator of meridian: https://reddit.com/r/jailbreak/comments/7q04s2/tutorial_how_to_install_filza_with_meridian/
