### ISSUE TITLE
make finding /bootstrap/ recursive

### ISSUE THREAD

**Issue by Geczy** [josephwalden13/tweak-installer#23]
So that if it finds bootstrap in ANY folder of a zip then it will copy that to the device

Not just in the root of the zip 

Here's an example zip to use

http://gmoran.me/downloads/FiveIconDockXI_0.1.zip

**Comment by josephwalden13** [comment]
Thanks for the suggestion! I've added it to the github but I'm not going to push it in a release yet. I'll release it alongside other things. Here's a prerelease containing the new code though :) https://github.com/josephwalden13/tweak-installer/blob/master/bin/Debug/1.1.2%20~%20prerelease.zip?raw=true
