### ISSUE TITLE
Error when installing HepaticKeyboard

### ISSUE THREAD

**Issue by Random260** [josephwalden13/tweak-installer#24]
My phone iphone x running 11.1.2

I installed hepatickeyboard and according to reddit tweaks that tweak should work but when I go to setting it says "There was an error loading the preference bundle for hepatic keyboard" Is that an issue on their end or on your end?

**Comment by josephwalden13** [comment]
Have you made sure dependencies are met? For example HapticKeyboard by @ca13ra1 (not sure which tweak you are using) depends on Cephei

**Comment by Brooktrout12** [comment]
I have the same issue. What do you mean by dependencies & how do you fix it or add them?

**Comment by ca13ra1** [comment]
You need Cephei as stated by @josephwalden13 and it’s not available for Electra since it’s techincally in beta and Cephei has yet to be made compatible. Therefore all my tweaks prefs will only work when it’s updated to support iOS 11. This issue should be closed.

**Comment by Brooktrout12** [comment]
Ok thank you :)
