### ISSUE TITLE
Error wiht instalation .ipa

### ISSUE THREAD

**Issue by D1mar0n** [josephwalden13/tweak-installer#25]
Today after installing a few apps (cracked from AppStore) and attempt to run them I get the notification on the iPhone screen that this version is not compatible with iOS 11! )) Even Torngat after the installation I was given such notification... I guess the problem in sign application?

**P.S.** Version 1.1.1 work perfectly...

**Comment by josephwalden13** [comment]
https://github.com/josephwalden13/tweak-installer/blob/master/bin/Debug/1.2.2%20beta.zip?raw=true

Try this version 🤔

**Comment by D1mar0n** [comment]
I've downloaded the 1.1.1 version again and it installed everything on phone his girl. Now download version on Your link and will try to work with her. In 5-10 minutes, write about the result.

**Comment by D1mar0n** [comment]
Tried to install the application installation was very long. After installing and trying to start the phone "gone" in safe mode...
**P.S.** The same application with version 1.1.1 installed quickly and works without any problems...

**Comment by D1mar0n** [comment]
iPhone 7 | iPhone 8+ after installing the application fail to start, generate error messages about incompatibility with iOS 11...

**Comment by nickch99** [comment]
Error "xxx needs to be updated..." after ipa installed.. (v1.2.2)
Seems the same problem reported by D1mar0n..
Device: iPad Pro 10.5 with electra b9
Anyway.. v1.1.1 works great..

**Comment by D1mar0n** [comment]
Continue to receive errors when you try to install or remove .ipa files...

>  Unhandled exception: System.TimeoutException: Timeout waiting for WinSCP to respond
    in WinSCP.Session.CheckForTimeout(String additional)
    in WinSCP.PatientFileStream.Read(Byte[] array, Int32 offset, Int32 count)
    in System.Xml.XmlTextReaderImpl.ReadData()
    in System.Xml.XmlTextReaderImpl.ParseText(Int32& startPos, Int32& endPos, Int32& outOrChars)
    inSystem.Xml.XmlTextReaderImpl.ParseText()
    inSystem.Xml.XmlTextReaderImpl.ParseElementContent()
    inSystem.Xml.XmlTextReaderImpl.Read()
    in WinSCP.SessionLogReader.DoRead()
    in WinSCP.SessionLogReader.Read(LogReadFlags flags)
    in WinSCP.ElementLogReader.Read(LogReadFlags flags)
    in WinSCP.SessionElementLogReader.Read(LogReadFlags flags)
    in WinSCP.ElementLogReader.Read(LogReadFlags flags)
    in WinSCP.Session.PutFiles(String localPath, String remotePath, Boolean remove, TransferOptions options)
    in Unjailbreaker.Program.<>c__DisplayClass16_2.<Main>b__3(String i)
    in System.Collections.Generic.List`1.ForEach(Action`1 action)
    in Unjailbreaker.Program.Main(String[] args)

**Comment by josephwalden13** [comment]
That's because of ssh cutting out and not my tool @D1mar0n . As for the xxx needs to be updated issue I have fixed that and will push it in my next build along with the other bug fixes

**Comment by D1mar0n** [comment]
Thank you very much for the answer! Tell me one more thing: when I want to completely remove the application, and there are options ... / y / n / a / which option should I choose?

Отправлено с iPhone

> 30 янв. 2018 г., в 17:31, josephwalden13 <notifications@github.com> написал(а):
> 
> That's because of ssh cutting out and not my tool @D1mar0n . As for the xxx needs to be updated issue I have fixed that and will push it in my next build along with the other bug fixes

**Comment by josephwalden13** [comment]
That depends. Normally you’d click A, but it depends which files got backed up. If you installed the tweak over system files it’ll ask you if you want to restore those files back when you remove it. Which files does it ask if you want to restore?

**Comment by D1mar0n** [comment]
I install the iNet Scanner.ipa application and I'm asked about maybe about 100 files I want to recover from? I want to completely remove this application and then install a new version of this App.

Отправлено с iPhone

> 30 янв. 2018 г., в 23:17, josephwalden13 <notifications@github.com> написал(а):
> 
> That depends. Normally you’d click A, but it depends which files got backed up. If you installed the tweak over system files it’ll ask you if you want to restore those files back when you remove it. Which files does it ask if you want to restore?
>

**Comment by josephwalden13** [comment]
Open “backup” then “Applications” and delete the folder for iNet Scanner. You must’ve installed it over itself before :D 

You should open “skip.list” and delete all of the files beginning with /Applications/iNet Scanner (they’ll all be together. The latest version of the tool will unfortunately not sign Applications correctly however. I’ve fixed it but I haven’t pushed the update yet, which I will do soon

**Comment by D1mar0n** [comment]
Thanks! 👍

Отправлено с iPhone

**Comment by D1mar0n** [comment]
To my surprise I found the folder "Backup" copies of these applications. So did everything as I did in similar situations many years ago when I went through Filaza (I have a modified version for the Electra) and scored in search of desired applications. looked at the list with found files and deleted is not necessary. After that the application installed without problems. ))

На 31.01.2018 6:49:12, Dima Ivanov <dimaivanov2001@gmail.com> писал:
Thanks! 👍


Отправлено с iPhone

31 янв. 2018 г., в 0:39, josephwalden13 <notifications@github.com [mailto:notifications@github.com]> написал(а):


Open “backup” then “Applications” and delete the folder for iNet Scanner. You must’ve installed it over itself before :D
You should open “skip.list” and delete all of the files beginning with /Applications/iNet Scanner (they’ll all be together. The latest version of the tool will unfortunately not sign Applications correctly however. I’ve fixed it but I haven’t pushed the update yet, which I will do soon

**Comment by josephwalden13** [comment]
https://drive.google.com/open?id=1A0puEyfAqZfZ1kT8ZLDMiLg4ks7I0cn4

This beta fixes app installation. I’ll publicly release it when I have sped it up a bit

**Comment by lone-wolf-akela** [comment]
Sorry I cannot download your beta installer. Google drive says it has virus and won't let me download it.
