### ISSUE TITLE
Filza stops working after 20 seconds

### ISSUE THREAD

**Issue by teefixx** [josephwalden13/tweak-installer#27]
When using Filza (installed by right click) for more than 20 seconds an error message appears "Main binary was modified, Please reinstall Filza"

iPhone 7
iOS 11.1.2
Electra beta 9
Tweak installer 1.22

**Comment by josephwalden13** [comment]
I can’t fix this because I don’t modify Filza at all. It’s working fine for me, and installs directly from PsychoTea’s tutorial so there’s nothing I can do unfortunately.
