### ISSUE TITLE
3DNoDiv10 not working

### ISSUE THREAD

**Issue by Brooktrout12** [josephwalden13/tweak-installer#31]
The tweak is supposed to be compatible with 11.1.2 but no changes take place. I used the latest 1.2.2 version.

**Comment by StalkerSea** [comment]
The changes are that the small semi-transparent lines that usually show up in the 3D touch gestures, shouldn't show up. Are you sure that there is no change? I'm going to try myself the tweak, but where did you downloaded it? I had it before and it was working perfectly.

**Comment by Brooktrout12** [comment]
Yes I‘m sure the seperators were still there after respring and reboot and reapplying the jailbreak. Thank you for your time!

**Comment by josephwalden13** [comment]
Maybe it isn't compatible. I can't test it unfortunatly (no 3d touch devices) however it should install like other tweaks so there's nothing I can do
