### ISSUE TITLE
Filza doesn't have the right permissions

### ISSUE THREAD

**Issue by jschmud** [josephwalden13/tweak-installer#33]
When I use beta 1.2.2 and right click and install Filza it installs fine but doesn't have root permissions. It will launch and I can see all of the files everywhere but if I try to delete a file or edit one, it says I don't have the correct permissions to do so. I imagine it is a problem with the signing of the app. I had the same issue when I manually installed it and signed it with jtool.

**Comment by josephwalden13** [comment]
I believe it’s an issue with the daemon. Not entirely sure though. Unfortusnlty, for now at least, this isn’t something I can fix
