### ISSUE TITLE
start menu error

### ISSUE THREAD

**Issue by joshuah345** [josephwalden13/tweak-installer#34]
![smenulanunchcapture](https://user-images.githubusercontent.com/29195927/35599200-9cadab8e-05f5-11e8-9bba-af6ccc5b6c62.png)

pressing continue button still works but settings get reset
and version 1.2.2 stil says 1.2 in the corner

**Comment by josephwalden13** [comment]
I’ll change the next version to store settings in a dedicated directory instead of in the directory it runs in to fix this. I’ll  also remember to change the version label
