### ISSUE TITLE
youtube++ 13.02.9 ipa  installation error

### ISSUE THREAD

**Issue by Crusherx** [josephwalden13/tweak-installer#35]
ipa file sideloads with cydia impactor and opens up fine.

Using the tweak installer (which was an incredibly long wait during preparing for installation and around 96%), i get an error saying the app needs to be updated to ios11.

![image](https://user-images.githubusercontent.com/35984250/35603936-d5c192e2-060d-11e8-8723-ded42ba3dcd2.png)

Device: Iphone8+
IOS: 11.1.2
App: YouTube.v13.02.9_v1.4r-91

**Comment by josephwalden13** [comment]
https://drive.google.com/open?id=1A0puEyfAqZfZ1kT8ZLDMiLg4ks7I0cn4

This beta will fix it. I’ll make a public issue when I’ve fixed the speed issues. I’ve sped it up but it’s still not as fast as I’d like.

**Comment by Crusherx** [comment]
It won't let me download the file above. I managed to install and run it using v1.1.1 as someone else suggested in one of the issue threads here.

Now the problem is whenever I download a video, it doesn't save. Sideload alternative makes the app fully functional though.

Perhaps there is some permission issue?
