### ISSUE TITLE
Show selected DEBs in UI

### ISSUE THREAD

**Issue by Geczy** [josephwalden13/tweak-installer#37]
1. Don't allow clicking install / uninstall if no DEBs are selected
2. If DEBs are selected, show which ones

**Comment by josephwalden13** [comment]
Will do in 1.3.1 / 1.4 (whichever comes first)

**Comment by Geczy** [comment]
The selected DEB isn't showing yet, is that intentional ?

**Comment by favna** [comment]
On top of this request it would also be nice if we could drag and drop debs into the window to queue them up

Also confirming the above comment based on v2.0
