### ISSUE TITLE
[Future Request] Open just an SSH session in the commandline

### ISSUE THREAD

**Issue by favna** [josephwalden13/tweak-installer#38]
Instead of doing some action like install or uninstall it would be nice to have a button which just opens an SSH session and lets us do our own commands. This way TweakInstaller can be even more a one-stop tool

**Comment by josephwalden13** [comment]
Good idea. I'll add this to 1.4 (or 1.3.1, whichever comes first)

**Comment by favna** [comment]
@josephwalden13 I see you manually closed this issue after making the 1.3.1 commit so I'd like to point you to this article which shows how you can close issues with keywords in commit messages. It gives a better and clearer overview on the issue and saves an otherwise manual action on your end

https://help.github.com/articles/closing-issues-using-keywords/

Example of the commit message: `1.3.1 (resolves #37 resolves #38)` would've closed both issues with just that 1 commit 0d46d7dfec2acafa5d50692d88318a0b75c729b2

**Comment by josephwalden13** [comment]
Oh cool, thanks. That’s so useful :D 

I’m still a bit of a github noob :D
