### ISSUE TITLE
Tweak Installer error

### ISSUE THREAD

**Issue by alexmaten** [josephwalden13/tweak-installer#39]
WinSCP.SessionRemoteException: Network error: Connection to "192.168.1.35" timed out.
   en WinSCP.SessionLogReader.Read(LogReadFlags flags)
   en WinSCP.ElementLogReader.Read(LogReadFlags flags)
   en WinSCP.SessionElementLogReader.Read(LogReadFlags flags)
   en WinSCP.CustomLogReader.TryWaitForNonEmptyElement(String localName, LogReadFlags flags)
   en WinSCP.CustomLogReader.WaitForNonEmptyElement(String localName, LogReadFlags flags)
   en WinSCP.Session.Open(SessionOptions sessionOptions)
   en Unjailbreaker.Program.Main(String[] args)

**Comment by josephwalden13** [comment]
Make sure you're using the right ip, password and port, and that your device is jailbroken. Maybe try rebooting and rejailbreaking if that's not the issue
