### ISSUE TITLE
Error installing iPA

### ISSUE THREAD

**Issue by LaxusiC** [josephwalden13/tweak-installer#4]
Im trying to install Cercube. Win 10 1703 64bit

![screenshot_1](https://user-images.githubusercontent.com/9650215/35277688-2872baa0-007a-11e8-92d5-76fbfa87047c.png)

**Comment by josephwalden13** [comment]
Seems like it’s an issue with the ssh client (seems like it’s just cut out mid way through). Use my tool to remove cercube by selecting the ipa and then clicking uninstall, and then click install to retry. After that it should work.

**Comment by LaxusiC** [comment]
I managed to install other apps, this happen only with cercube. I guess it's because the app file size is too big.

Another issue is Hotspot Shield++ (Downloaded from hollr2099) i cannot install VPN profile

EDIT: Error happen when im trying to uninstall Cercube like you said, same error

EDIT 2: I have to keep my device on screen so that i don't have any error, successfully installed Cercube

EDIT 3: Looks like something is broken, you cannot sign in to your account, happen with other apps also (Facebook++, etc, ..)

**Comment by josephwalden13** [comment]
I was going to suggest leaving the phone unlocked but I see you’ve already found that works :)
The error described in edit3 seems to be in all of the ++ tweaks but not others such as cercube 
.ill take a look at it but I’m not sure if I’ll be able to fix it yet. Same with hotspot shield

**Comment by josephwalden13** [comment]
Unfortunately I’m not sure how I can fix this, as it seems to be different on a case by case basis, however I will leave this thread open in the hope that someone else might be able to work out a solution

**Comment by LaxusiC** [comment]
@josephwalden13 nvm, that might be a problem with Electra JB because maybe no sandbox escaped yet XD. Thank you for the tool, save me a lot of time

**Comment by josephwalden13** [comment]
Although some app issues are caused because of the sandboxing, I don’t think hotspotshield++ is. I believe it’s because when I sign it with my current method it is stripped of its entitlements (specifically VPN entitlement). I’m currently trying to find a solution to this problem, but I’m not currently sure of an eta. Coolstars sandbox escape update will fix most apps though

**Comment by josephwalden13** [comment]
I’ll close this and open a new updated issue
