### ISSUE TITLE
cannot uninstall tweak

### ISSUE THREAD

**Issue by teefixx** [josephwalden13/tweak-installer#41]
Hi 
Uninstall of com.malcolmhall.wifipasswords.deb (bigness repo) doesn't work.
Even if I reinstall it it's still there after uninstall...

No errors during uninstall, uicache and respring works.

thanx
[com.malcolmhall.wifipasswords.deb.zip](https://github.com/josephwalden13/tweak-installer/files/1685919/com.malcolmhall.wifipasswords.deb.zip)

**Comment by josephwalden13** [comment]
Did it prompt you to restore any files? The tweak may have gotten mixed up in your backup folder and been restored after uninstalling

**Comment by teefixx** [comment]
You were right. I tried it again with a clean (newly downloaded and extracted“ version 1.31 of you installer. It worked with that.

Thanx



Am 1. Februar 2018 um 17:37:19, josephwalden13 (notifications@github.com<mailto:notifications@github.com>) schrieb:

Did it prompt you to restore any files? The tweak may have gotten mixed up in your backup folder and been restored after uninstalling
