### ISSUE TITLE
v1.3 always crash even respring/uicache (electra b10)

### ISSUE THREAD

**Issue by nickch99** [josephwalden13/tweak-installer#42]
Connecting
Unknown Error. Please use the big red bug report link and include some form of crash report. Error report copying to clipboard.

Unhandled Exception: WinSCP.SessionRemoteException: Connection has been unexpectedly closed. Server sent command exit status 0.
Authentication log (see session log for details):
Using username "root".

Authentication failed.
   at Unjailbreaker.Program.Main(String[] args)

**Comment by pinheiro1007** [comment]
WinSCP.SessionRemoteException: Connection has been unexpectedly closed. Server sent command exit status 0.
Authentication log (see session log for details):
Using username "root".

Authentication failed.
   in WinSCP.SessionLogReader.Read(LogReadFlags flags)
   in WinSCP.ElementLogReader.Read(LogReadFlags flags)
   in WinSCP.SessionElementLogReader.Read(LogReadFlags flags)
   in WinSCP.CustomLogReader.TryWaitForNonEmptyElement(String localName, LogReadFlags flags)
   in WinSCP.CustomLogReader.WaitForNonEmptyElement(String localName, LogReadFlags flags)
   in WinSCP.Session.Open(SessionOptions sessionOptions)
   in Unjailbreaker.Program.Main(String[] args)

**Comment by josephwalden13** [comment]
Oh. I know why. One sec
