### ISSUE TITLE
Error v1.3

### ISSUE THREAD

**Issue by pinheiro1007** [josephwalden13/tweak-installer#43]
WinSCP.SessionRemoteException: Connection has been unexpectedly closed. Server sent command exit status 0.
Authentication log (see session log for details):
Using username "root".

Authentication failed.
   in WinSCP.SessionLogReader.Read(LogReadFlags flags)
   in WinSCP.ElementLogReader.Read(LogReadFlags flags)
   in WinSCP.SessionElementLogReader.Read(LogReadFlags flags)
   in WinSCP.CustomLogReader.TryWaitForNonEmptyElement(String localName, LogReadFlags flags)
   in WinSCP.CustomLogReader.WaitForNonEmptyElement(String localName, LogReadFlags flags)
   in WinSCP.Session.Open(SessionOptions sessionOptions)
   in Unjailbreaker.Program.Main(String[] args)

**Comment by josephwalden13** [comment]
Use the latest version
