### ISSUE TITLE
root access denied

### ISSUE THREAD

**Issue by joshuah345** [josephwalden13/tweak-installer#46]
in new version 1.3.1, puTTY was added as a terminal, but logging in as root fails. ssh by clicking install or uninstall works fine

**Comment by teefixx** [comment]
Here it works quite well, it logs in as root but takes some time...

iPhone 7, iOS 11.1.2

**Comment by josephwalden13** [comment]
It should auto log in to putty, but I think I may know what the problem is. Firstly did you set ip, password and port correctly in my tool, and secondly does your password by any chance contain a space? If so that’ll cause it to fail to login (I will fix that soon)

**Comment by joshuah345** [comment]
no it doesnt contain spaces, its setup properly i can use install and uninstall buttons

**Comment by josephwalden13** [comment]
Hmm. If you download this into the same folder as tweak installer and run it does it work? 

https://github.com/josephwalden13/tweak-installer/blob/master/bin/Debug/miniTerminal.exe?raw=true

(It will be slow cause its a test thing mostly, although when I finish updating it it'll hopefully be quite useful)

**Comment by josephwalden13** [comment]
https://github.com/josephwalden13/tweak-installer/blob/master/bin/Debug/latest.zip?raw=true
