### ISSUE TITLE
Error while installing theme .deb

### ISSUE THREAD

**Issue by ErikD-H** [josephwalden13/tweak-installer#47]
![error](https://user-images.githubusercontent.com/36059672/35713300-9b2c5008-0794-11e8-9709-16de484a4882.jpg)

**Comment by ErikD-H** [comment]
installed another theme and went through flawlessly...should i delete this issue ?

**Comment by josephwalden13** [comment]
Hmm. I’ll take a look into it when I can

**Comment by josephwalden13** [comment]
Fixed the problem that caused the first error :)
