### ISSUE TITLE
can't install tweak when replace

### ISSUE THREAD

**Issue by joekempis** [josephwalden13/tweak-installer#48]
cannot replace file y/n/a

**Comment by josephwalden13** [comment]
What’s the error message?

**Comment by joekempis** [comment]
error like this :

![img_0246](https://user-images.githubusercontent.com/25734086/35723902-e275b40c-0836-11e8-837e-c1e556992b50.jpg)

**Comment by nickch99** [comment]
the same error while you press 'n'..

**Comment by joekempis** [comment]
yes.. the same error when you press y/n/a

**Comment by josephwalden13** [comment]
Please could you press “1.3” in the top corner of the gui and try again (this will give me more information to help fix the problem. I’m sure it’s a stupid mistake I’ve made though :D)

**Comment by jpbeauch65** [comment]
Same error for me. No mather what I choose Y/N/A the error is the same as above. The only way I was able to install the tweak was to uninstall it first and then try again.
