### ISSUE TITLE
Error with installation of soma ipa file

### ISSUE THREAD

**Issue by marchino123** [josephwalden13/tweak-installer#5]
Ipa such as spotify or adblock don’t work...I have tried with different source but when I open the app It quicly closes

**Comment by josephwalden13** [comment]
I have looked into the Spotify++ issue, and it seems to be a special case. It appears to be signed as it should, but it won't launch. Just download spotify from the AppStore and use my tweak installer to install spotilife (the tweak thats in spotify++) from http://julio.xarold.com/files-deb/com.julioverne.spotilife_0.8_iphoneos-arm.deb and you'll have all of the Spotify++ features in the appstore version. As for Adblock, I am not going to look into it as I do not support piracy. If you really want it then I reccomend you use VShare to install it.

**Comment by josephwalden13** [comment]
Actually, I may be close to fixing Spotify & if this works AdBlock probably will too

**Comment by josephwalden13** [comment]
Ok so I've fixed it, but I just need to update tweak installer to do it automatically

**Comment by marchino123** [comment]
Thanks sir... I wait your update❤️

**Comment by josephwalden13** [comment]
Unfortunately I’m not sure how I can fix this, as it seems to be different on a case by case basis, however I will leave this thread open in the hope that someone else might be able to work out a solution

**Comment by josephwalden13** [comment]
Actually I will close this thread since the other one is the same problem. Hopefully someone can help with this
