### ISSUE TITLE
Filza Error "Main binary was modified"

### ISSUE THREAD

**Issue by FrostyBits77** [josephwalden13/tweak-installer#50]
When I Install Filza through tweak-installer, I get an error saying "Main binary was modified. Please reinstall Filza." and then when I tap OK the crashes.

**Comment by josephwalden13** [comment]
Unfortunately I cannot fix this because it’s the signing that does this, and without signing it won’t launch anyway. From using it I’ve noticed that it only seems to do that for me if I click apps manager. Everything else works fine
