### ISSUE TITLE
use direct command for uicache

### ISSUE THREAD

**Issue by joshuah345** [josephwalden13/tweak-installer#53]
as seen in my reddit post, (https://www.reddit.com/r/jailbreak/comments/7uu63k/question_uicache_doesnt_work/) uicache command can fail unless run directly from /bootstrap/usr/bin
so update ssh command to cd to directory and run ./uicache

**Comment by josephwalden13** [comment]
Only problem is that this tool is compatible with more than just electra. Uicache is only found in /bootstrap/ in electra so that'd break compatability. I could add a check to see if /bootstrap/ exists and run it from there instead if it does however
