### ISSUE TITLE
Error v2.0 instal deb/ipa

### ISSUE THREAD

**Issue by pinheiro1007** [josephwalden13/tweak-installer#57]
WinSCP.SessionRemoteException: Connection has been unexpectedly closed. Server sent command exit status 0.
Authentication log (see session log for details):
Using username "root".

Authentication failed.
   in WinSCP.SessionLogReader.Read(LogReadFlags flags)
   in WinSCP.ElementLogReader.Read(LogReadFlags flags)
   in WinSCP.SessionElementLogReader.Read(LogReadFlags flags)
   in WinSCP.CustomLogReader.TryWaitForNonEmptyElement(String localName, LogReadFlags flags)
   in WinSCP.CustomLogReader.WaitForNonEmptyElement(String localName, LogReadFlags flags)
   in WinSCP.Session.Open(SessionOptions sessionOptions)
   in Tweak_Installer.Main.getSession(String ip, String user, String password, Int32 port)

**Comment by josephwalden13** [comment]
Try again. This means the ssh server was closed and isn't actually a problem with my tool
