### ISSUE TITLE
Make it work with zip files for electra

### ISSUE THREAD

**Issue by Geczy** [josephwalden13/tweak-installer#6]
File structures like /bootstrap/x/x/
Example: http://gmoran.me/downloads/FiveIconDockXI_0.1.zip

Or like /*.plist, /*.dylib
Example: https://github.com/Ominousness/MitsuhaXI/releases/download/v0.1.2/MitsuhaXI_Spotify.zip

**Comment by Geczy** [comment]
Or at least output an error if it didn't copy over anything. Right now it makes it look like it works

**Comment by josephwalden13** [comment]
Good idea. I’ll add it to the next build. Not sure about the second example but the first one would be easy to implement. For the second one I’ll try to do it but it’s kinda hard to tell where to put them if they’re just supplied in /. If I don’t get it working for example2 I’ll at least add an error message

**Comment by Geczy** [comment]
If there are only two files of dylib and plist, you can just assume it's a tweak and pop it in the `SBInject`

Otherwise yeah display an error

Thanks for checking it

**Comment by josephwalden13** [comment]
So if a zip contains a folder called bootstrap It'll install as usual. If it contains dylibs and plists it'll install them to SBInject. Coming in beta9 :)

**Comment by Geczy** [comment]
@josephwalden13 did you forget to commit the changes to github? I only see the beta9 zip, bt where i the source?

**Comment by josephwalden13** [comment]
I committed it shortly after releasing it (so that people don't get update notifications before its uploaded)
https://github.com/josephwalden13/tweak-installer/blob/master/Program.cs
Starts at line 210
