### ISSUE TITLE
Error installing Cercube

### ISSUE THREAD

**Issue by SaDizz** [josephwalden13/tweak-installer#66]
WinSCP.SessionRemoteException: Network error: Connection to "192.168.1.100" timed out.
   in WinSCP.SessionLogReader.Read(LogReadFlags flags)
   in WinSCP.ElementLogReader.Read(LogReadFlags flags)
   in WinSCP.SessionElementLogReader.Read(LogReadFlags flags)
   in WinSCP.CustomLogReader.TryWaitForNonEmptyElement(String localName, LogReadFlags flags)
   in WinSCP.CustomLogReader.WaitForNonEmptyElement(String localName, LogReadFlags flags)
   in WinSCP.Session.Open(SessionOptions sessionOptions)
   in Tweak_Installer.Main.getSession(String ip, String user, String password, Int32 port)

**Comment by josephwalden13** [comment]
check ssh login settings
