### ISSUE TITLE
how long takes Uicache ?

### ISSUE THREAD

**Issue by ghost** [josephwalden13/tweak-installer#73]
How long takes the Uicache? i installed flex 3 beta (with this tutorial http://www.gottotech.com/2018/02/tutorial-downloadinstall-flex-3-beta.html ) and the last step is running the Uicache, but nothing happens
"Connecting
Connected to SSH
Running uicache"

Is the only thing i get. How long does this take ? Or is it already finished?

**Comment by josephwalden13** [comment]
Normally it would print “Done” afterwards but in some cases it skips it. I’ll take a look into it, however I reccomend installing Flex via Cydia now that it’s updated

**Comment by josephwalden13** [comment]
If flex appears on the home screen it’s finished correctly :)

**Comment by ghost** [comment]
not even with Cydia is flex working xD
