### ISSUE TITLE
uninstalling deb files causes cydia error (2)

### ISSUE THREAD

**Issue by snos2** [josephwalden13/tweak-installer#76]
using tweak installer to uninstall deb files works great BUT after the uninstall it cleans some empty files 
one of those file is the "updates" folder from /Library/dpkg/updates
after it deletes this file cydia returns error code 
sub-process /usr/libexec/cydia/cydo returned an error code (2)
and tweaks will no longer install or uninstall via cydia 
fixing the issue requires ssh into the device and re-creating the folder 
thanks

**Comment by josephwalden13** [comment]
I wrote the code to avoid this, I just forgot to enable it *facepalm*

Fixed in latest version
