### ISSUE TITLE
main:71 ipa does not exist

### ISSUE THREAD

**Issue by td009** [josephwalden13/tweak-installer#77]
when i want to install ipa from tweak intaller 2.1 , it gives every ipa this error --> appinst: main:71 The file /electra/tweakinstaller/appname.ipa does not exist.

**Comment by josephwalden13** [comment]
Please could you try this build https://github.com/josephwalden13/tweak-installer/blob/776ede83372325da2f0669d7933f416a73c0996a/bin/Debug/latest.zip?raw=true and see if it works :)

**Comment by josephwalden13** [comment]
If it works for you I'll push it as an update
