### ISSUE TITLE
unable to install ipa's

### ISSUE THREAD

**Issue by zedge05** [josephwalden13/tweak-installer#78]
Hi, I was unable to install ipa's wherein I already installed appsync under Karen's repo. I'm using the v2.1.1.
Thank you.
![capture](https://user-images.githubusercontent.com/31645454/37188803-fe3a45ca-238b-11e8-8994-a305b247296b.PNG)

**Comment by josephwalden13** [comment]
You need to install appinst (from Karen’s repo) as well :)
