### ISSUE TITLE
please solve

### ISSUE THREAD

**Issue by gmpiprani** [josephwalden13/tweak-installer#80]
![untitled1](https://user-images.githubusercontent.com/38314841/38669234-41a41e7e-3e5f-11e8-83d7-07503c8f4673.png)
![untitled2](https://user-images.githubusercontent.com/38314841/38669241-468fff7a-3e5f-11e8-8725-f3de403ce360.png)

**Comment by josephwalden13** [comment]
You need to set the device IP and root password

You can find the IP by following these steps http://www.macinstruct.com/node/547

And your root password is alpine
