### ISSUE TITLE
i use password alpine please know me perfect password

### ISSUE THREAD

**Issue by gmpiprani** [josephwalden13/tweak-installer#81]
![untitled4](https://user-images.githubusercontent.com/38314841/38688183-ecfbb2dc-3e91-11e8-9401-47a0433540ae.png)

**Comment by josephwalden13** [comment]
As with the last two reports you sent, it's the same issue. I even sent you a link showing how to find the IP address. Until you follow the instructions I sent please stop spamming me with error reports which aren't even errors
