### ISSUE TITLE
ios 11.1.1 sur IPAD air A1474 16G + Electra 1.0.2 + Tweak Installer 2.1.1

### ISSUE THREAD

**Issue by berunous** [josephwalden13/tweak-installer#82]
hello 
loading the file "com.ifone.offlinemaps_4.0.4-1.deb"  show the windows Tweak installer 
![windows tweak installer](https://user-images.githubusercontent.com/38850910/39417675-3bbb1ea4-4c56-11e8-847d-bb963a738d05.png). but I show nothing on the IPAD spring board ???

can you help me thanks

**Comment by josephwalden13** [comment]
It appears that when installing via dpkg I forgot to check for the need to run uicache. If you click the uicache button it should appear :)

**Comment by berunous** [comment]
where is the uicache button ???
if it's a command what is the syntax and on which terminal sorry but I'm not a specialist
Thank you for the quick reply

**Comment by berunous** [comment]
sorry I did not look well. the UIcache button is on tweak install. The action on the button has made appear the icon of the application on the springboard thank you

**Comment by josephwalden13** [comment]
No problem :)
