### ISSUE TITLE
install path

### ISSUE THREAD

**Issue by Danga123** [josephwalden13/tweak-installer#83]
Hello and thanks for your tool and all the hard work you put in it! 

I have used it alot in the past. Unfortunately, the uninstall wouldnt work properly in an earlier versio so i began to run out of space and at some point reset the device. Problem is that this did not delete all apps/games i had installed.

I manually removed app from /Applications/*.app but that didnt free up as much as expected. 

Could you kindly help me out here?

**Comment by josephwalden13** [comment]
Hmm

I'm not sure what could be taking up the space but this command could help you work out where the storage is being used

`cd / && du -h --max-depth=5 | sort -hr`

But it will output so much data that any terminal application will likely crash. If it still crashes or lags out you could add `> files.txt` to the end of the command and open the file files.txt which will hopefully be quicker

The command scans through folders and tells you the sizes (ordered from highest to lowest for convenience)

Hopefully this works :)

**Comment by Danga123** [comment]
Thanks already, simple but usefull command :-)

Here is the result:

- 14G .
- 6.6G	./private/var
- 6.6G	./private
- 4.0G	./private/var/containers
- 4.0G	./Applications
- 3.9G	./private/var/containers/Bundle/Application
- 3.9G	./private/var/containers/Bundle
- 2.4G	./System/Library
- 2.4G	./System
- 1.8G	./private/var/mobile
- 1.1G	./private/var/mobile/Containers/Data
- 1.1G	./private/var/mobile/Containers
- 1.1G	./System/Library/Caches

**Comment by josephwalden13** [comment]
For comparison here's what I get:

- 20G	.
- 16G	./private/var
- 16G	./private
- 8.5G	./private/var/mobile
- 6.8G	./private/var/mobile/Containers/Data
- 6.8G	./private/var/mobile/Containers
- 5.2G	./private/var/containers/Bundle/Application
- 5.2G	./private/var/containers/Bundle
- 5.2G	./private/var/containers
- 2.4G	./System/Library
- 2.4G	./System
- 1.1G	./System/Library/Caches
- 215M	./Applications

For whatever reason your /Applications folder is almost 20x the size of mine. 

Try running this command (it'll show the sizes of everything in /Applications). The culprit could be a hidden folder

`cd /Applications && du -h --max-depth=1 | sort -hr`

**Comment by josephwalden13** [comment]
Also turns out adding `| head -50` to the end of the command limits the output to 50 which will make it much less laggy

**Comment by Danga123** [comment]
There are indeed 2-3 large apps listed in that directory, but thats ok because they are currently installed and functional. Unfortunately, this is still not where the "dead files" are located.

[Screenshot](https://ibb.co/ccgNyn)

On that screenshot you can see that "system" or "other" is taking around 26GB. When i used your tool in the past it would take quite a while to transfer the content of large IPAs. This is when i noticed that during the transfer, occupied space was added to "other" instead of a regular app. That is also why im thinking there must be some leftovers of previous tweak installer installations.

**Comment by josephwalden13** [comment]
I'm not sure why it's showing that. There definitely isn't 26GB of "other". Everything installed by tweak installer does go into other but the output of the first command shows that you've only used 14gb of storage so it must be a system bug. If you run the first command again as root does the output change?

**Comment by Danga123** [comment]
Same result :-/ Im out of ideas. As i cannot restore due to missing blobs, ill have to live with it i guess.

**Comment by josephwalden13** [comment]
Hmm. What version of electra are you using? If it's an older version you could try uninstalling it after removing all tweaks and resetting in settings? 

You could also try delectra? I think this is partially an issue with iOS 11 and not just the jailbreak or tweak installer

**Comment by Danga123** [comment]
I already removed electra and did a reset, hoping this would help, but apparently only a restore will result in a clean file structure.

**Comment by josephwalden13** [comment]
https://twitter.com/jakeashacks/status/1000096719269441537?s=21

Maybe this? (sorry I didn’t reply in so long)

**Comment by Danga123** [comment]
Hey Joseph! Thanks for your reply. Unfortunately, i will not be able to check, even if it would have been interesting. I ended updating to 11.3.1 which fixed the issue. Lost the possibility to jailbreak for now, but space was more important.
