### ISSUE TITLE
method driver missing

### ISSUE THREAD

**Issue by MichaeloJr** [josephwalden13/tweak-installer#85]
when cydia is refreshing, i get this error in red... " the method driver /usr/lib/apt/methods/http could not be found.

**Comment by josephwalden13** [comment]
Have you tried reinstalling apt?

**Comment by MichaeloJr** [comment]
Tried absolutely everything, faulty packages. I’ve moved onto a different iPhone but when I dig it back out I’ll post everything here.

On 11 Feb 2019, at 12:11, josephwalden13 <notifications@github.com<mailto:notifications@github.com>> wrote:


Have you tried reinstalling apt?

**Comment by josephwalden13** [comment]
1.
